/**
 * Admin Demo Data
 * Realistic mock data for demonstrating admin capabilities
 */

import type {
  OrganizationWithDetails,
  UserWithMembership,
  JiraConnectionWithWorkspace,
  SyncLog,
  AuditLogRecord,
  LicensingInfo,
  FeatureFlag,
} from "./api";

// Demo Organizations
export const demoOrganizations: OrganizationWithDetails[] = [
  {
    id: "org-1",
    name: "Acme Corporation",
    slug: "acme-corp",
    plan: "enterprise",
    status: "active",
    settings: {},
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2026-05-01T14:30:00Z",
    workspaces: [
      { id: "ws-1", name: "Engineering", memberCount: 45 },
      { id: "ws-2", name: "Product", memberCount: 12 },
      { id: "ws-3", name: "Platform", memberCount: 8 },
    ],
    subscription: {
      plan: "enterprise",
      status: "active",
      seatsTotal: 100,
      seatsUsed: 65,
    },
  },
  {
    id: "org-2",
    name: "TechStart Inc",
    slug: "techstart",
    plan: "pro",
    status: "active",
    settings: {},
    createdAt: "2024-06-20T08:00:00Z",
    updatedAt: "2026-04-28T11:15:00Z",
    workspaces: [{ id: "ws-4", name: "Main", memberCount: 18 }],
    subscription: {
      plan: "pro",
      status: "active",
      seatsTotal: 25,
      seatsUsed: 18,
    },
  },
  {
    id: "org-3",
    name: "Global Finance Ltd",
    slug: "global-finance",
    plan: "enterprise",
    status: "active",
    settings: {},
    createdAt: "2023-11-01T09:00:00Z",
    updatedAt: "2026-05-02T16:45:00Z",
    workspaces: [
      { id: "ws-5", name: "Core Banking", memberCount: 32 },
      { id: "ws-6", name: "Mobile Apps", memberCount: 15 },
      { id: "ws-7", name: "Infrastructure", memberCount: 10 },
      { id: "ws-8", name: "Data Platform", memberCount: 8 },
    ],
    subscription: {
      plan: "enterprise",
      status: "active",
      seatsTotal: 100,
      seatsUsed: 65,
    },
  },
  {
    id: "org-4",
    name: "StartupXYZ",
    slug: "startupxyz",
    plan: "free",
    status: "active",
    settings: {},
    createdAt: "2026-03-10T14:00:00Z",
    updatedAt: "2026-04-25T09:30:00Z",
    workspaces: [{ id: "ws-9", name: "Team", memberCount: 4 }],
    subscription: {
      plan: "free",
      status: "active",
      seatsTotal: 5,
      seatsUsed: 4,
    },
  },
  {
    id: "org-5",
    name: "MegaCorp Industries",
    slug: "megacorp",
    plan: "enterprise",
    status: "suspended",
    settings: { suspendReason: "Payment overdue", suspendedAt: "2026-04-15T00:00:00Z" },
    createdAt: "2023-05-20T11:00:00Z",
    updatedAt: "2026-04-15T00:00:00Z",
    workspaces: [
      { id: "ws-10", name: "R&D", memberCount: 55 },
      { id: "ws-11", name: "Operations", memberCount: 30 },
    ],
    subscription: {
      plan: "enterprise",
      status: "past_due",
      seatsTotal: 100,
      seatsUsed: 85,
    },
  },
  {
    id: "org-6",
    name: "HealthTech Solutions",
    slug: "healthtech",
    plan: "pro",
    status: "active",
    settings: {},
    createdAt: "2024-09-05T10:00:00Z",
    updatedAt: "2026-05-01T08:00:00Z",
    workspaces: [
      { id: "ws-12", name: "Clinical", memberCount: 20 },
      { id: "ws-13", name: "Platform", memberCount: 8 },
    ],
    subscription: {
      plan: "pro",
      status: "active",
      seatsTotal: 25,
      seatsUsed: 28,
    },
  },
];

// Demo Users
export const demoUsers: UserWithMembership[] = [
  {
    id: "user-1",
    email: "john.smith@acme.com",
    fullName: "John Smith",
    displayName: "John S.",
    avatarUrl: null,
    isAdmin: false,
    workspaceId: "ws-1",
    createdAt: "2024-01-15T10:00:00Z",
    membership: {
      id: "mem-1",
      role: "owner",
      status: "active",
      joinedAt: "2024-01-15T10:00:00Z",
    },
    identities: [
      { provider: "jira", providerAccountId: "jira-12345", displayName: "John Smith" },
    ],
  },
  {
    id: "user-2",
    email: "sarah.johnson@acme.com",
    fullName: "Sarah Johnson",
    displayName: "Sarah J.",
    avatarUrl: null,
    isAdmin: false,
    workspaceId: "ws-1",
    createdAt: "2024-02-01T09:00:00Z",
    membership: {
      id: "mem-2",
      role: "admin",
      status: "active",
      joinedAt: "2024-02-01T09:00:00Z",
    },
    identities: [
      { provider: "jira", providerAccountId: "jira-12346", displayName: "Sarah Johnson" },
    ],
  },
  {
    id: "user-3",
    email: "mike.chen@acme.com",
    fullName: "Mike Chen",
    displayName: "Mike C.",
    avatarUrl: null,
    isAdmin: false,
    workspaceId: "ws-1",
    createdAt: "2024-03-15T14:00:00Z",
    membership: {
      id: "mem-3",
      role: "member",
      status: "active",
      joinedAt: "2024-03-15T14:00:00Z",
    },
    identities: [],
  },
  {
    id: "user-4",
    email: "emma.wilson@techstart.io",
    fullName: "Emma Wilson",
    displayName: "Emma W.",
    avatarUrl: null,
    isAdmin: false,
    workspaceId: "ws-4",
    createdAt: "2024-06-20T08:00:00Z",
    membership: {
      id: "mem-4",
      role: "owner",
      status: "active",
      joinedAt: "2024-06-20T08:00:00Z",
    },
    identities: [
      { provider: "jira", providerAccountId: "jira-22345", displayName: "Emma Wilson" },
    ],
  },
  {
    id: "user-5",
    email: "david.park@globalfinance.com",
    fullName: "David Park",
    displayName: "David P.",
    avatarUrl: null,
    isAdmin: false,
    workspaceId: "ws-5",
    createdAt: "2023-11-01T09:00:00Z",
    membership: {
      id: "mem-5",
      role: "owner",
      status: "active",
      joinedAt: "2023-11-01T09:00:00Z",
    },
    identities: [
      { provider: "jira", providerAccountId: "jira-32345", displayName: "David Park" },
      { provider: "slack", providerAccountId: "slack-abc123", displayName: "david.park" },
    ],
  },
];

// Demo JIRA Connections
export const demoJiraConnections: JiraConnectionWithWorkspace[] = [
  {
    id: "jira-conn-1",
    workspaceId: "ws-1",
    cloudId: "cloud-123",
    siteName: "acme.atlassian.net",
    siteUrl: "https://acme.atlassian.net",
    isActive: true,
    lastSyncAt: "2026-05-03T01:00:00Z",
    lastSyncStatus: "completed",
    storiesSynced: 1247,
    workspaceName: "Engineering",
    organizationId: "org-1",
    organizationName: "Acme Corporation",
  },
  {
    id: "jira-conn-2",
    workspaceId: "ws-2",
    cloudId: "cloud-123",
    siteName: "acme.atlassian.net",
    siteUrl: "https://acme.atlassian.net",
    isActive: true,
    lastSyncAt: "2026-05-03T01:15:00Z",
    lastSyncStatus: "completed",
    storiesSynced: 342,
    workspaceName: "Product",
    organizationId: "org-1",
    organizationName: "Acme Corporation",
  },
  {
    id: "jira-conn-3",
    workspaceId: "ws-4",
    cloudId: "cloud-456",
    siteName: "techstart.atlassian.net",
    siteUrl: "https://techstart.atlassian.net",
    isActive: true,
    lastSyncAt: "2026-05-03T00:45:00Z",
    lastSyncStatus: "partial",
    storiesSynced: 523,
    workspaceName: "Main",
    organizationId: "org-2",
    organizationName: "TechStart Inc",
  },
  {
    id: "jira-conn-4",
    workspaceId: "ws-5",
    cloudId: "cloud-789",
    siteName: "globalfinance.atlassian.net",
    siteUrl: "https://globalfinance.atlassian.net",
    isActive: true,
    lastSyncAt: "2026-05-02T23:30:00Z",
    lastSyncStatus: "failed",
    storiesSynced: 2156,
    workspaceName: "Core Banking",
    organizationId: "org-3",
    organizationName: "Global Finance Ltd",
  },
  {
    id: "jira-conn-5",
    workspaceId: "ws-9",
    cloudId: "cloud-999",
    siteName: "startupxyz.atlassian.net",
    siteUrl: "https://startupxyz.atlassian.net",
    isActive: true,
    lastSyncAt: "2026-05-03T02:00:00Z",
    lastSyncStatus: "completed",
    storiesSynced: 87,
    workspaceName: "Team",
    organizationId: "org-4",
    organizationName: "StartupXYZ",
  },
];

// Demo Sync Logs
export const demoSyncLogs: SyncLog[] = [
  {
    id: "sync-1",
    status: "completed",
    syncType: "scheduled",
    startedAt: "2026-05-03T01:00:00Z",
    completedAt: "2026-05-03T01:02:34Z",
    durationMs: 154000,
    storiesSynced: 1247,
    storiesCreated: 12,
    storiesUpdated: 45,
    usersDiscovered: 3,
    errors: [],
    warnings: ["15 stories missing story points"],
  },
  {
    id: "sync-2",
    status: "partial",
    syncType: "manual",
    startedAt: "2026-05-03T00:45:00Z",
    completedAt: "2026-05-03T00:48:12Z",
    durationMs: 192000,
    storiesSynced: 498,
    storiesCreated: 8,
    storiesUpdated: 23,
    usersDiscovered: 1,
    errors: [{ code: "RATE_LIMIT", message: "Rate limited by JIRA API, partial sync completed" }],
    warnings: [],
  },
  {
    id: "sync-3",
    status: "failed",
    syncType: "scheduled",
    startedAt: "2026-05-02T23:30:00Z",
    completedAt: "2026-05-02T23:30:45Z",
    durationMs: 45000,
    storiesSynced: 0,
    storiesCreated: 0,
    storiesUpdated: 0,
    usersDiscovered: 0,
    errors: [{ code: "AUTH_EXPIRED", message: "JIRA OAuth token expired. Reconnection required." }],
    warnings: [],
  },
];

// Demo Failed Syncs
export const demoFailedSyncs = [
  {
    ...demoSyncLogs[2],
    workspaceName: "Core Banking",
    organizationId: "org-3",
    organizationName: "Global Finance Ltd",
    siteName: "globalfinance.atlassian.net",
    siteUrl: "https://globalfinance.atlassian.net",
  },
];

// Demo Audit Logs
export const demoAuditLogs: AuditLogRecord[] = [
  {
    id: "audit-1",
    adminUserId: "admin-1",
    adminEmail: "admin@forge.com",
    action: "organization.create",
    entityType: "organization",
    entityId: "org-6",
    organizationId: "org-6",
    workspaceId: null,
    oldValues: null,
    newValues: { name: "HealthTech Solutions", plan: "pro" },
    createdAt: "2026-05-02T10:30:00Z",
  },
  {
    id: "audit-2",
    adminUserId: "admin-1",
    adminEmail: "admin@forge.com",
    action: "subscription.plan_change",
    entityType: "subscription",
    entityId: "sub-2",
    organizationId: "org-2",
    workspaceId: null,
    oldValues: { plan: "free" },
    newValues: { plan: "pro" },
    createdAt: "2026-05-01T14:15:00Z",
  },
  {
    id: "audit-3",
    adminUserId: "admin-1",
    adminEmail: "admin@forge.com",
    action: "feature_flag.toggle",
    entityType: "feature_flag",
    entityId: "flag-1",
    organizationId: "org-1",
    workspaceId: null,
    oldValues: { enabled: false },
    newValues: { flagName: "advanced_analytics", enabled: true },
    createdAt: "2026-04-30T09:00:00Z",
  },
  {
    id: "audit-4",
    adminUserId: "admin-1",
    adminEmail: "admin@forge.com",
    action: "organization.suspend",
    entityType: "organization",
    entityId: "org-5",
    organizationId: "org-5",
    workspaceId: null,
    oldValues: { status: "active" },
    newValues: { status: "suspended" },
    createdAt: "2026-04-15T00:00:00Z",
  },
  {
    id: "audit-5",
    adminUserId: "admin-1",
    adminEmail: "admin@forge.com",
    action: "jira.force_sync",
    entityType: "jira_connection",
    entityId: "jira-conn-4",
    organizationId: "org-3",
    workspaceId: "ws-5",
    oldValues: null,
    newValues: { fullSync: true },
    createdAt: "2026-04-28T16:00:00Z",
  },
  {
    id: "audit-6",
    adminUserId: "admin-1",
    adminEmail: "admin@forge.com",
    action: "user.role_change",
    entityType: "workspace_member",
    entityId: "mem-2",
    organizationId: "org-1",
    workspaceId: "ws-1",
    oldValues: { role: "member" },
    newValues: { role: "admin" },
    createdAt: "2026-04-25T11:30:00Z",
  },
];

// Demo Feature Flags
export const demoFeatureFlags: FeatureFlag[] = [
  { id: "flag-1", flagName: "multi_jira", enabled: true, config: {} },
  { id: "flag-2", flagName: "advanced_analytics", enabled: true, config: {} },
  { id: "flag-3", flagName: "cross_workspace_analytics", enabled: true, config: {} },
  { id: "flag-4", flagName: "custom_rubrics", enabled: true, config: {} },
  { id: "flag-5", flagName: "api_access", enabled: true, config: {} },
  { id: "flag-6", flagName: "white_label", enabled: false, config: {} },
  { id: "flag-7", flagName: "sso", enabled: false, config: {} },
];

// Demo Licensing Info
export const demoLicensingInfo: LicensingInfo = {
  subscription: {
    id: "sub-1",
    plan: "enterprise",
    status: "active",
    seatsTotal: 100,
    seatsUsed: 65,
  },
  featureFlags: demoFeatureFlags,
  limits: { withinLimits: true, violations: [] },
  planLimits: {
    seats: 100,
    workspaces: 10,
    jiraConnections: 5,
    features: [
      "basic_scoring",
      "advanced_analytics",
      "custom_rubrics",
      "multi_jira",
      "api_access",
    ],
  },
};

// Summary stats
export const demoStats = {
  totalOrganizations: demoOrganizations.length,
  activeOrganizations: demoOrganizations.filter((o) => o.status === "active").length,
  totalJiraConnections: demoJiraConnections.length,
  failedSyncs24h: demoFailedSyncs.length,
  totalAdminActions: demoAuditLogs.length,
  planBreakdown: {
    free: demoOrganizations.filter((o) => o.plan === "free").length,
    pro: demoOrganizations.filter((o) => o.plan === "pro").length,
    enterprise: demoOrganizations.filter((o) => o.plan === "enterprise").length,
  },
};

// Audit action summary
export const demoAuditSummary = [
  { action: "organization.create", count: 2 },
  { action: "subscription.plan_change", count: 3 },
  { action: "feature_flag.toggle", count: 5 },
  { action: "jira.force_sync", count: 8 },
  { action: "user.role_change", count: 4 },
  { action: "organization.suspend", count: 1 },
  { action: "user.link_identity", count: 12 },
];
